app:
    resource: "@AppBundle/Controller/"
    type:     annotation


app_rest:
    type:     rest
    prefix:   /api/v1
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    defaults:
      _format:  json